version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eventbridge2sns"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yx2bo9xuftfl"
s3_prefix = "eventbridge2sns"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
