AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - Lamdba put events to EventBridge filter/pipe to SNS Topics

Resources:
  BankBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: bluebank-bus

  EventsGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Policies:
        EventBridgePutEventsPolicy:
          EventBusName: !Ref BankBus
  # Define the SNS topic #1
  ReserveBankTopic:
    Type: AWS::SNS::Topic

  # Define the SNS topic #2
  TransactionWarehouseTopic:
    Type: AWS::SNS::Topic

  # Define the event rule to filter for events to Topic 1
  EventRuleReserveBank:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventRule ReserveBank"
      EventBusName: !Ref BankBus
      EventPattern:
        account:
          - !Sub '${AWS::AccountId}'
        source:
          - "reservebank.bluebank.events"
        detail-type:
          - "BOP transaction"
        detail:
          bop_reportable:
            - "Yes"
      Targets:
        - Arn: !Ref ReserveBankTopic
          Id: "ReserveBankTopic"

  # Define the event rule to filter for events to Topic 2
  EventRuleTransactionWarehouseTopic:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventRule TransactionWarehouseTopic"
      EventBusName: !Ref BankBus
      EventPattern:
        account:
          - !Sub '${AWS::AccountId}'
        source:
          - "bankbranch.bluebank.events"
        detail-type:
          - "BOP transaction"
        detail:
          bop_reportable:
            - "Yes"
      Targets:
        - Arn: !Ref TransactionWarehouseTopic
          Id: "SNSTransactionWarehouseTopic"

  # Allow EventBridge to invoke SNS Topic ReserveBank
  EventBridgeToSnsPolicyReserveBank:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: [
        "SNS:GetTopicAttributes",
        "SNS:SetTopicAttributes",
        "SNS:AddPermission",
        "SNS:RemovePermission",
        "SNS:DeleteTopic",
        "SNS:Subscribe",
        "SNS:ListSubscriptionsByTopic",
        "SNS:Publish"
      ]
          Resource: !Ref ReserveBankTopic
      Topics:
        - !Ref ReserveBankTopic

  # Allow EventBridge to invoke SNS Topic TransactionWarehouseTopic
  EventBridgeToSnsPolicyTransactionWarehouseTopic:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: [
        "SNS:GetTopicAttributes",
        "SNS:SetTopicAttributes",
        "SNS:AddPermission",
        "SNS:RemovePermission",
        "SNS:DeleteTopic",
        "SNS:Subscribe",
        "SNS:ListSubscriptionsByTopic",
        "SNS:Publish"
      ]
          Resource: !Ref TransactionWarehouseTopic
      Topics:
        - !Ref TransactionWarehouseTopic

Outputs:
  ReserveBankTopicName:
    Description: SNS ReserveBankTopic topic name
    Value: !GetAtt ReserveBankTopic.TopicName
  ReserveBankTopicArn:
    Description: SNS ReserveBankTopic topic ARN
    Value: !Ref ReserveBankTopic
  TransactionWarehouseTopicName:
    Description: SNS TransactionWarehouseTopic topic name
    Value: !GetAtt TransactionWarehouseTopic.TopicName
  TransactionWarehouseTopicArn:
    Description: SNS TransactionWarehouseTopic topic ARN
    Value: !Ref TransactionWarehouseTopic
